routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('menuPrincipal');
});
//PEDIDOS
Route::resource('/pedidos', 'PedidosController');
//CALIFICACIÓN
Route::resource('/calificacion', 'CalificacionController');
//CATEGORIAS
Route::get('/pedidos/get_categorias/{id}', 'CategoriasController@getCategorias');
//PRODUCTOS
Route::get('/pedidos/get_productos/{id}', 'ProductosController@getProductos');
//PEDIDO PRODUCTO
Route::get('/pedidos/get_pedidoProductos/{id}', 'PedidoProductoController@getPedidoProductos');

resources/views/calificacion.blade.php
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset('css/general.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/star-rating-svg.css')}}">
    <link rel="stylesheet" href="{{asset('css/modal.css')}}">
    <title>Clasificación</title>
</head>

<body class="body-color">
    <div class="container">
        <div class="row">
            <div class="col mb-3 mt-5">
                <img class="mx-auto d-block img-fluid" src="{{asset('img/iconos/reward.png')}}" width="20%" height="20%">
            </div>
        </div>
        <div class="row">
            <div class="col mt-2">
                <h3 class="text-center text-light">Gracias por su preferencia, sea libre de calificar nuestro
                    servicio.</h3>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col mt-5">
                    <span class="calificacion d-flex justify-content-center"></span>
                    <h3 class="live-rating text-light"></h3>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="clasificacionModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="col pt-3">
                        <h5 class="text-light text-center">Muchas gracias por su calificación, esperamos verte pronto ;)</h5>
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="{{ url('/') }}" class="btn btn-success">Cerrar</a>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="{{asset('js/jquery.star-rating-svg.min.js')}}"></script>
    <script src="{{asset('js/calificacion.js')}}"></script>
</body>

</html>

resources/views/estadosOrden.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ config('app.name') }}</title>
        <link rel="shortcut icon" href="{{asset('img/logos/orderprocess.ico')}}" />
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{{asset('css/general.css')}}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <script src="{{ asset('js/jquery-3.4.1.min.js') }}"></script>
        <script src="{{ asset('js/estadoPedidos.js') }}"></script>
    </head>
    <body class="body-color">
            <div class="container py-5">
                <div class="row">
                    <div class="col-sm-12 table-responsive">
                        <h2 class="text-center text-white mb-5 mt-3">Estado de las Ordenes</h2>
                        <table class="table table-striped table-dark table-bordered" id="pedidosTable">
                            <thead>
                                <tr>
                                    <th scope="col" rowspan="1">#</th>
                                    <th scope="col" rowspan="1">Hora</th>
                                    <th scope="col" rowspan="1">Mesa</th>
                                    <th scope="col" rowspan="1">Estado</th>
                                    <th scope="col" colspan="2">Productos</th>
                                    <th scope="col" rowspan="1">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($pedidos as $pedido)
                                    <tr>
                                        <td>{{$pedido->id_pedido}}</td>
                                        <td>{{$pedido->hora_pedido}}</td>
                                        <td>{{$pedido->num_mesa}}</td>
                                        <td>
                                            @switch($pedido->estado)
                                                @case(0)
                                                    <div class="text-warning">
                                                        En Espera
                                                    </div>
                                                    @break
                                                @case(1)
                                                    <div class="text-info">
                                                        Preparando
                                                    </div>
                                                    @break
                                                @case(2)
                                                    <div class="text-success">
                                                        Listo
                                                    </div>
                                                    @break
                                            @endswitch
                                        </td>
                                        <td>
                                            <div class="col empty" id="pedido{{$pedido->id_pedido}}">
                                                <ul id="productos{{$pedido->id_pedido}}">
                                                    <div class="col-sm-1"><span id="loader{{$pedido->id_pedido}}" class="text-light d-none"><i class="fas fa-spinner fa-pulse"></i></span></div>
                                                </ul>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="col">
                                                <div class= "row d-flex justify-content-center">
                                                    <button type="button" class="table-btn-ver btn btn-info" title="Cargar/Ocultar Productos">
                                                        <i class="fas fa-eye"></i>
                                                    </button>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class= "row d-flex justify-content-center">
                                                <button type="button" class="table-btn-editar btn btn-success" title="Editar Pedido">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col">
                                <a class="btn btn-warning float-right" href="{{ url('/') }}">Volver</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    </body>
</html>

resources/views/menuPrincipal.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ config('app.name') }}</title>
        <link rel="shortcut icon" href="{{asset('img/logos/orderprocess.ico')}}" />
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{{asset('css/general.css')}}">

    </head>
    <body class="body-color">
            <div class="container pb-5">
                <div class="row justify-content-center">
                    <div class="col-7">
                        @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                            @if(Session::has('alert-' . $msg))
                                <div class="alert alert-{{ $msg }} alert-dismissible fade show">{{ Session::get('alert-' . $msg) }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif
                        @endforeach
                    </div>
                    <div class="container col-6 mt-5">
                        <div class="row">
                            <a class="mx-auto" href="{{ route('pedidos.create') }}">
                                <img class="mx-auto d-block img-fluid" src="{{asset('img/iconos/order-food.png')}}" width="50%" height="50%" title="Ingresar Pedido" alt="Ingresar Pedido">
                            </a>
                        </div>
                        <div class="row">
                            <h3 class="text-light mt-1 mx-auto">Ingresar Orden</h3>
                        </div>
                    </div>
                    <div class="container col-6 mt-5">
                        <div class="row">
                            <a class="mx-auto" href="{{ route('pedidos.index') }}">
                                <img class="mx-auto d-block img-fluid" src="{{asset('img/iconos/order.png')}}" width="50%" height="50%" title="Ver estado de Pedidos" alt="Ver estado de Pedidos">
                            </a>
                        </div>
                        <div class="row">
                            <h3 class="text-light mt-1 mx-auto">Estados de Orden</h3>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="container col-6 mt-4 pb-5">
                        <div class="row">
                            <a class="mx-auto" href="{{ route('calificacion.index') }}">
                                <img class="mx-auto d-block img-fluid" src="{{asset('img/iconos/reward.png')}}" width="50%" height="50%" title="Ingresar Pedido" alt="Ingresar Pedido">
                            </a>
                        </div>
                        <div class="row">
                            <h3 class="text-light mt-1 mx-auto">Dar Calificación</h3>
                        </div>
                    </div>
                </div>
            </div>
            {{-- <footer class="footer footer-color">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7 text-light mx-auto">Iconos hechos por
                            <a href="https://www.freepik.com/" title="Freepik">Freepik</a> en
                            <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> está licenciado por
                            <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
                        </div>
                    </div>
                </div>
            </footer> --}}
            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        </body>
</html>